name: mvvm_clean
packages:
  - core/**
  - features/**

comands:
  bootstrap:
    environment:
      sdk: ^3.8.1

    dependencies:
      dio: ^5.8.0

    dev_dependencies: 
      flutter_test:
        sdk: flutter
      flutter_lints: ^5.0.0